version: '3.7'

services:
  prediction_service:
    build: 
      context: ./prediction-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - TORCHSERVE_HOST=http://host.docker.internal:8080
      - PREDICTION_TIMEOUT=60
    volumes:
      - ./prediction-service/:/app/
      - ./images/:/data
    ports:
      - 8002:8000
    depends_on:
      - rabbitmq
    networks:
      - my_network

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  torchserve:
    image: pytorch/torchserve:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./model_store:/home/model-server/model_store
    environment:
      - MODEL_STORE=/home/model-server/model_store
    command:
      - "torchserve"
      - "--start"
      - "--model-store"
      - "/home/model-server/model_store"
      - "--models"
      - "fastrcnn=fastrcnn.mar"
      - "nst=nst.mar"
    networks:
      - my_network

networks:
  my_network: