version: '3.7'

services:
  prediction_service:
    build: ./prediction-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./prediction-service/:/app/
    ports:
      - 8002:8000